name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '23'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build Gradle Project
        run: ./gradlew build

      - name: Execute Gradle Test
        run: ./gradlew test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Gradle Tests
          path: 'build/test-results/test/*.xml'
          reporter: java-junit
          fail-on-error: true
