name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '23'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Execute Gradle Build
        run: ./gradlew build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '23'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Gradle Test
        run: ./gradlew test

      - name: Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Gradle Tests
          path: 'build/test-results/test/*.xml'
          reporter: java-junit
          fail-on-error: true
